// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

=== Post deployment: AWS Config and AWS CloudTrail log permissions

[start=1]
. Security Hub uses service-linked https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config.html[AWS Config rules^]. Make sure that AWS Config is turned on and recording all supported resources, including global resources, in all accounts and regions where Security Hub is deployed. You are not charged by AWS Config for these service-linked rules. You are only charged according to https://aws.amazon.com/security-hub/pricing/[AWS Security Hub pricing^].

. This Quick Start uses an AWS Key Management Service (AWS KMS) key to remediate the link:#_coverage[PCI.CloudTrail.1 control]. The AWS KMS key must have permissions to encrypt/decrypt AWS CloudTrail logs in the AWS account in which this Quick Start is deployed. So, after deploying this Quick Start, make sure you update the AWS KMS key policy with the AWS account ID. To do this, navigate to the AWS KMS console and search for a key with an alias of "PCI-CMK". Then, see link:https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-kms-key-policy-for-cloudtrail.html#create-kms-key-policy-for-cloudtrail-policy-sections[Required CMK policy sections for use with CloudTrail^] for instructions to enable CloudTrail log permissions.

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
AWS Security Hub begins to run security checks within 2 hours after you deploy the PCI DSS and Foundational Security Best Practices controls. After the initial check, subsequent checks will occur on a periodic or change-triggered basis, depending on the control. For more information, see https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-schedule.html[Schedule for running security checks^].

In the following exercise, we will test a remediation of the link:#_coverage[PCI EC2.2] control. This control states that the VPC default security group should prohibit inbound and outbound traffic, and it is evaluated on a change-triggered basis. To do this, we will purposefully misconfigure security group settings in the EC2 console to allow traffic. This should trigger a Security Hub finding which remediates the security issue.

. Perform Misconfiguration: Navigate to the EC2 console and then Security Groups in the EC2 Console, select the default security group for the default VPC and edit inbound rules by adding an SSH rule (port 22) to IP address 0.0.0.0/0 and click on Save.  Make a note of the Security Group ARN.
. To view the resource change-triggered check, navigate to Security Hub and click on Findings to locate the finding that corresponds to the misconfiguration above.
. To remediate a finding, select the check box next to the finding and click Actions. From the drop-down menu on actions select the action you would like to use to remediate based on the Security Group Identifier noted earlier. In this case select the “PCI EC2.2” action.
. As per the flow of the solution approach for the Quick Start, you should see a message saying that findings were successfully sent to CloudWatch Events.
. To further validate the flow of the solution approach for the Quickstart, navigate to Systems Manager and click on Automation. You should see a successful automation execution that corresponds to the security group related remediation.
. To confirm the remediation was successful, navigate back to the EC2 Console, and then Security Groups and you will notice that the inbound rule change we made earlier by adding an SSH rule and IP address 0.0.0.0/0 has been removed in accordance with the remediation required by PCI EC2.2

== Best practices for using {partner-product-name} on AWS
AWS categorizes each AWS Security Hub service action into one of five access levels: List, Read, Write, Permissions management, or Tagging. To allow a large group of users to access List and Read Security Hub actions, and only a small group to access Write action, use specific managed IAM policies. For more information, see https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html[Security best practices in IAM^].

Security Hub ingests findings generated from integrated providers (both third-party services using https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html[AWS Security Finding Format (ASFF)^].

== Security
This Quick Start follows security best practices and guidelines as documented in link:https://docs.aws.amazon.com/securityhub/latest/userguide/security.html[Security in AWS Security Hub^].