// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
After you enable the PCI DSS or Foundational Security Best Practices controls, AWS Security Hub begins to run checks within 2 hours. After the initial check, the schedule for each control may be either periodic or change-triggered.

* Periodic checks run automatically within 12 hours after the most recent run. You cannot change the interval.
* Change-triggered checks run when the associated resource changes state. Even if the resource does not change state, the updated at time for change-triggered checks is refreshed every 18 hours. This helps to indicate that the control is still enabled.

Let’s test a remediation deployed by the Quick Start deployment by using a resource change-triggered check. In order to test an automated remediation, we will perform a misconfiguration that triggers a Security Hub Finding on a resource change-triggered check.  Specifically, we will look at the Foundational Security Best Practices Control - [PCI EC2.2]. The VPC default security group should prohibit inbound and outbound traffic.

. Perform Misconfiguration: Navigate to the EC2 console and then Security Groups in the EC2 Console, select the default security group for the default VPC and edit inbound rules by adding an SSH rule (port 22) to IP address 0.0.0.0/0 and click on Save.  Make a note of the Security Group ARN.
. To view the resource change-triggered check, navigate to Security Hub and click on Findings to locate the finding that corresponds to the misconfiguration above.
. To remediate a finding, select the check box next to the finding and click Actions. From the drop-down menu on actions select the action you would like to use to remediate based on the Security Group Identifier noted earlier. In this case select the “PCI EC2.2” action.
. As per the flow of the solution approach for the Quick Start, you should see a message saying that findings were successfully sent to CloudWatch Events.
. To further validate the flow of the solution approach for the Quickstart, navigate to Systems Manager and click on Automation. You should see a successful automation execution that corresponds to the security group related remediation.
. To confirm the remediation was successful, navigate back to the EC2 Console, and then Security Groups and you will notice that the inbound rule change we made earlier by adding an SSH rule and IP address 0.0.0.0/0 has been removed in accordance with the remediation required by PCI EC2.2

== Best practices for using {partner-product-name} on AWS
AWS categorizes each AWS Security Hub service action into one of five access levels: List, Read, Write, Permissions management, or Tagging. Use specific managed IAM policies for different types of Security Hub users to allow a large group of users to access List and Read Security Hub actions and allow only a small group of users to access the Security Hub Write actions.  With Security Hub, findings generated from integrated providers (both third-party services and AWS services) are ingested using a standard findings format.

== Security
This Quick Start follows security best practices and guidelines as documented in link:https://docs.aws.amazon.com/securityhub/latest/userguide/security.html[Security in AWS Security Hub].
