// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.
. Use the Region selector in the navigation bar to select the AWS Region where you want to deploy the Quick Start.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the Amazon Machine Image (AMI) for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-short-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start
You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

WARNING: This Quick Start deploys automated workflows to remediate security compliance issues that modify your AWS account. We do not recommend deploying this Quick Start in a production environment before appropriate evaluation and link:#_test_the_deployment[testing].

Deploy PCI DSS and AWS FSBP remediations::
PCI DSS and AWS FSBP remediations are each packaged in two templates. To deploy PCI DSS, choose the link to launch the first PCI DSS template and follow steps 1–8 provided. After deploying the first template, choose the link to launch the second PCI DSS template and repeat steps 1–8. Repeat this entire process to deploy the two AWS FSBP templates.

* https://fwd.aws/KDjxv[Launch the first PCI DSS template^].
* https://fwd.aws/bnKqj[Launch the second PCI DSS template^].
* https://fwd.aws/z7bKp[Launch the first AWS FSBP template^].
* https://fwd.aws/m376K[Launch the second AWS FSBP template^].

[start=1]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for the deployment is built. The template is launched in the {default_deployment_region} Region by default.
. On the *Select Template* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify Details* page, provide the stack name. For the second PCI DSS template only, also specify an email address. This is used specifically for link:#_coverage[PCI.CW.1] control notifications. 
. Review and choose *Next*.