// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.
. Use the Region selector in the navigation bar to select the AWS Region where you want to deploy the Quick Start.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the Amazon Machine Image (AMI) for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-short-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start
NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

WARNING: This reference architecture contains automatic remediations for PCI DSS Controls and Foundational Security Best Practices. These remediations may make changes to your AWS account. We do not recommend using this reference architecture in a production environment before appropriate evaluation and testing


Deploy PCI-DSS remediation templates::
PCI-DSS standards are packaged in two templates. Templates must be deployed in the order they are provided in the following instructions.

[start=1]
. https://first_pci_launch_link[Launch the first PCI Remediation template].
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for {partner-product-short-name} will be built. The template is launched in the {default_deployment_region} Region by default.
. On the *Select Template* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify Details* page, provide the stack name. For the second template only, also specify an email address. This is used specifically for link:#_coverage[PCI.CW.1] control notifications. 
. Review and choose *Next*.
. On the *Options* page, you can specify tags (key-value pairs) for resources in your stack and set advanced options. When you’re done, choose *Next*.
. On the *Review* page, review and confirm the template settings. Under *Capabilities*, select the two check boxes to acknowledge that the template creates IAM resources and that it might require the capability to auto-expand macros.
. Choose *Create* to deploy the stack. Monitor the status of the stack. When the status is CREATE_COMPLETE, the deployment is complete.
. To view the resources created, see the URLs displayed in the *Outputs* tab for the stack.
. https://second_fsbp_launch_link[Launch the second PCI Remediation template].
. Follow steps 2-9 for the second template deployment.

[start=1]
Deploy Foundational Security Best Practices remediation templates::
Foundational Security Best Practices standards are packaged in two templates. Templates must be deployed in the order they are provided in the following instructions.

. https://first_fsbp_template_link[Launch the first Foundational Security Best Practices remediation template].
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for {partner-product-short-name} will be built. The template is launched in the {default_deployment_region} Region by default.
. On the *Select Template* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify Details* page, provide the stack name. Review and choose *Next*.
. On the *Options* page, you can specify tags (key-value pairs) for resources in your stack and set advanced options. When you’re done, choose *Next*.
. On the *Review* page, review and confirm the template settings. Under *Capabilities*, select the two check boxes to acknowledge that the template creates IAM resources and that it might require the capability to auto-expand macros.
. Choose *Create* to deploy the stack. Monitor the status of the stack. When the status is CREATE_COMPLETE, the deployment is complete.
. To view the resources created, see the URLs displayed in the *Outputs* tab for the stack.
. https://second_fsbp_template_link[Launch the second Foundational Security Best Practices remediation template].
. Follow steps 2-9 for the second template deployment.

