// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.
. Use the Region selector in the navigation bar to choose the AWS Region where you want to deploy the Quick Start Cloud Formation templates

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-short-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

[start=1]
For PCI-DSS Controls::
. The Quick Start is packaged into 2 CloudFormation templates:
.. aws-security-hub-pci-remediations-template1.yml
.. aws-security-hub-pci-remediations-template2.yml
. Template Deployment Order: *The aws-security-hub-pci-remediations-template1.yml template must be deployed before the aws-security-hub-pci-remediations-template2.yml template*. The aws-security-hub-pci-remediations-template1.yml template provisions the AWS Systems Manager automation documents that are leveraged by the aws-security-hub-pci-remediations-template2.yml template to remediate the Security Hub Findings.
. Follow the steps below to deploy each template
.. Check the Region that’s displayed in the upper-right corner of the navigation bar and change it if necessary. The template is launched in the US East (N.Virginia) Region by default.
.. On the Select Template page, keep the default setting for the template URL, and then choose Next.
.. On the Specify Details page, provide the stack name. The aws-security-hub-pci-remediations-template1.yml template takes no input parameters. For the aws-security-hub-pci-remediations-template2.yml specify an "Email Address" as a parameter. This is used for notifications for PCI.CW.1.  Review and choose Next.
.. On the Options page, you can specify tags (key-value pairs) for resources in your stack and set advanced options. When you’re done, choose Next.
.. On the Review page, review and confirm the template settings. Under Capabilities, select the two check boxes to acknowledge that the template will create IAM resources and that it might require the capability to auto-expand macros.
.. Choose Create to deploy the stack.
.. Monitor the status of the stack. When the status is CREATE_COMPLETE, the deployment of the template is complete.
.. Use the URLs displayed in the Outputs tab for the stack to view the resources that were created.

[start=1]
For Foundational Security Best Practices Controls::
. The Quick Start is packaged into 2 CloudFormation templates:
.. aws-security-hub-fsbp-remediations-template1.yml
.. aws-security-hub-fsbp-remediations-template2.yml
. Template Deployment Order: *The aws-security-hub-fsbp-remediations-template1.yml template must be deployed before the aws-security-hub-fsbp-remediations-template2.yml template*. The aws-security-hub-fsbp-remediations-template1.yml template provisions the AWS Systems Manager automation documents that are leveraged by the aws-security-hub-fsbp-remediations-template2.yml template to remediate the Security Hub Findings.
. Follow the steps below to deploy each template
.. Check the Region that’s displayed in the upper-right corner of the navigation bar and change it if necessary. The template is launched in the US East (N.Virginia) Region by default.
.. On the Select Template page, keep the default setting for the template URL, and then choose Next.
.. On the Specify Details page, provide the stack name. The template takes no input parameters. Review and choose Next.
.. On the Options page, you can specify tags (key-value pairs) for resources in your stack and set advanced options. When you’re done, choose Next.
.. On the Review page, review and confirm the template settings. Under Capabilities, select the two check boxes to acknowledge that the template will create IAM resources and that it might require the capability to auto-expand macros.
.. Choose Create to deploy the stack.
.. Monitor the status of the stack. When the status is CREATE_COMPLETE, the deployment of the template is complete.
.. Use the URLs displayed in the Outputs tab for the stack to view the resources that were created.
