// Replace the content in <>
// Briefly describe the software. Use consistent and clear branding.
// Include the benefits of using the software on AWS, and provide details on usage scenarios.
// Describe how the software works on AWS.>
Customers require compliance with established security and regulatory controls when migrating workloads to AWS but face numerous challenges. It is a multi-step process that involves reference to standards and regulatory requirements, individual policy definitions, remeditaion workflows, and exception procedures. Furthermore, several remediation steps may require extensive hands-on experience with AWS as individual findings require multiple configuration steps for remediation. This activity is manual, error prone, and results in a high MTTR (Mean Time To Remediation) for customers thus increasing risk and operational costs.

AWS Security Hub provides checks that offer automated detection of findings of configuration noncompliance with PCI DSS and AWS FSBP. This Quick Start leverages the AWS Security Hub service and provides customers with an AWS native implementation for automated real time remediations for PCI DSS and AWS FSBP policy violations detected by AWS Security Hub.

=== Solution approach

This Quick Start is based on the following solution approach:

[start=1]
. Leverages AWS Security Hub directly to provide automated and continuous detection and recording of PCI DSS and AWS FSBP findings.
. Provides AWS Systems Manager automation documents for automated remediation of AWS Security Hub findings. All automation documents are automatically provisioned via an AWS CloudFormation template.
. Provides integration of AWS Security Hub custom actions with AWS Systems Manager automation documents to provide real-time remediations of AWS Security Hub PCI DSS and AWS FSBP findings as follows:
.. Leverages the ability of AWS Security Hub to send findings associated with custom actions to Amazon CloudWatch Events as Security Hub Findings - Custom Action events.
.. The CloudWatch Events rule invokes the corresponding AWS Lambda function as the target for the Security Hub custom action event.
.. The AWS Lambda function processes the finding using the AWS Security Finding Format (ASFF) and invokes the corresponding AWS Systems Manager Automation Document with the input from the ASFF finding.
.. AWS Systems Manager remediates the Security Hub finding.

=== Coverage
This Quick Start deploys automated remediation workflows for the following controls.

PCI DSS::
* [PCI.AutoScaling.1] Amazon EC2 Auto Scaling groups associated with a load balancer should use health checks.
* [PCI.CloudTrail.1] AWS CloudTrail logs should be encrypted at rest using AWS Key Management System (AWS KMS) keys.
* [PCI.CloudTrail.2] AWS CloudTrail log file validation should be enabled.
* [PCI.CloudTrail.3] AWS CloudTrail log file validation should be enabled.
* [PCI.CloudTrail.4] AWS CloudTrail trails should be integrated with Amazon CloudWatch Logs.
* [PCI.CodeBuild.2] AWS CodeBuild project environment variables should not contain clear text credentials.
* [PCI.CW.1] A log metric filter and alarm should be available to the "root" user.
* [PCI.Config.1] AWS Config should be enabled.
* [PCI.EC2.1] Amazon Elastic Block Storage (Amazon EBS) snapshots should not be publicly restorable.
* [PCI.EC2.2] Amazon Virtual Private Cloud (Amazon VPC) default security group should prohibit inbound and outbound traffic.
* [PCI.EC2.3] Unused Amazon Elastic Compute Cloud (Amazon EC2) security groups should be removed.
* [PCI.EC2.4] Unused Amazon EC2 Elastic IP addresses should be removed.
* [PCI EC2.5] Security groups should not allow inbound traffic from 0.0.0.0/0 to port 22.
* [PCI.EC2.6] Amazon VPC flow logging should be enabled in all VPCs.
* [PCI.IAM.1] AWS Identity and Access Management (IAM) root user access key should not exist.
* [PCI.IAM.2] IAM users should not have IAM policies attached.
* [PCI.IAM.3] IAM policies should not allow full administrative privileges.
* [PCI.KMS.1] AWS KMS key rotation should be enabled.
* [PCI.Lambda.1] AWS Lambda functions should prohibit public access.
* [PCI.Lambda.2] AWS Lambda functions should be in a VPC.
* [PCI.RDS.1] Amazon Relational Database Service (Amazon RDS) snapshots should prohibit public access.
* [PCI.RDS.2] Amazon RDS database instances should prohibit public access.
* [PCI.Redshift.1] Amazon Redshift clusters should prohibit public access.
* [PCI.S3.1] Amazon Simple Storage Service (Amazon S3) buckets should prohibit public write access.
* [PCI.S3.2] S3 buckets should prohibit public read access.
* [PCI.S3.3] S3 buckets should have cross-Region replication enabled.
* [PCI.S3.4] S3 buckets should have server-side encryption enabled.
* [PCI.SSM.1] Amazon EC2 instances managed by AWS Systems Manager should have a patch compliance status of *COMPLIANT* after a patch installation.

AWS FSBP::
* [EC2.3] Attached Amazon EBS volumes should be encrypted at rest.
* [GuardDuty.1] Amazon GuardDuty should be enabled.
* [IAM.3] IAM .access keys should be rotated every 90 days or less.
* [Lambda.1] AWS Lambda functions should prohibit public access.
* [Lambda.2] AWS Lambda functions should use latest runtimes.
* [RDS.3] Amazon RDS database instances should have encryption at rest enabled.
* [SSM.1] Amazon EC2 instances should be managed by AWS Systems Manager.

Additional AWS FSBP coverage provided when the PCI DSS remediation templates are deployed::
The coverage for remediations of each of these FSBP controls is provided by deploying the PCI remediation templates aws-security-hub-pci-remediations-template1.template and aws-security-hub2-pci-remediations-template1.template2.

* [AutoScaling.1] Amazon EC2 Auto Scaling groups associated with a load balancer should use load balancer health checks.
* [CloudTrail.1] AWS CloudTrail should be enabled and configured with at least one multi-Region trail.
* [CloudTrail.2] AWS CloudTrail should have encryption at rest enabled.
* [CodeBuild.2] AWS CodeBuild project environment variables should not contain clear text credentials.
* [Config.1] AWS Config should be enabled.
* [EC2.1] Only authorized users should be able to share Amazon EBS snapshots publicly.
* [EC2.2] The VPC default security group should not allow inbound and outbound traffic.
* [IAM.1] IAM policies should not allow full administrative privileges.
* [IAM.2] IAM users should not have IAM policies attached.
* [IAM.4] IAM root user access key should not exist.
* [IAM.7] Password policies for IAM users should have strong configurations.
* [S3.1] S3 Block Public Access setting should be enabled.
* [S3.2] S3 buckets should prohibit public read access.
* [S3.3] S3 buckets should prohibit public write access.
* [S3.4] S3 buckets should have server-side encryption enabled.
* [RDS.1] Amazon RDS snapshots should be private.
* [RDS.2] Amazon RDS database instances should prohibit public access.
* [SSM.2] Amazon EC2 instances managed by Systems Manager should have a patch compliance status of *COMPLIANT* after a patch installation

WARNING: The PCI DSS compliance standard in AWS Security Hub is designed to help you with ongoing PCI DSS security activities. The controls cannot verify if your systems are compliant with the PCI DSS standard. They can't replace internal efforts or guarantee that you will pass a PCI DSS assessment. Security Hub does not check procedural controls that require manual evidence collection.